// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type DownloadResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    downloaded_files?: Array<string> | null;
    message: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type PostDownloadRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    url: string;
    /**
     * Pass additional args to yt-dlp
     */
    yt_dlp_args?: string;
};

export type SortDownloadsResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    files_with_errors: Array<string> | null;
    moved_files: Array<string> | null;
};

export type DownloadResponseBodyWritable = {
    downloaded_files?: Array<string> | null;
    message: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type PostDownloadRequestWritable = {
    url: string;
    /**
     * Pass additional args to yt-dlp
     */
    yt_dlp_args?: string;
};

export type SortDownloadsResponseBodyWritable = {
    files_with_errors: Array<string> | null;
    moved_files: Array<string> | null;
};

export type PostApiV1DownloadData = {
    body: PostDownloadRequestWritable;
    path?: never;
    query?: never;
    url: '/api/v1/download';
};

export type PostApiV1DownloadErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostApiV1DownloadError = PostApiV1DownloadErrors[keyof PostApiV1DownloadErrors];

export type PostApiV1DownloadResponses = {
    /**
     * OK
     */
    200: DownloadResponseBody;
};

export type PostApiV1DownloadResponse = PostApiV1DownloadResponses[keyof PostApiV1DownloadResponses];

export type PostApiV1SortDownloadsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/sort-downloads';
};

export type PostApiV1SortDownloadsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostApiV1SortDownloadsError = PostApiV1SortDownloadsErrors[keyof PostApiV1SortDownloadsErrors];

export type PostApiV1SortDownloadsResponses = {
    /**
     * OK
     */
    200: SortDownloadsResponseBody;
};

export type PostApiV1SortDownloadsResponse = PostApiV1SortDownloadsResponses[keyof PostApiV1SortDownloadsResponses];

export type GetApiV1StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status';
};

export type GetApiV1StatusErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetApiV1StatusError = GetApiV1StatusErrors[keyof GetApiV1StatusErrors];

export type GetApiV1StatusResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetApiV1StatusResponse = GetApiV1StatusResponses[keyof GetApiV1StatusResponses];
