// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type DownloadNotFoundEvent = {
    [key: string]: never;
};

export type DownloadResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
    task_id: string;
};

export type DownloadStdoutNewLineEvent = {
    line: string;
};

export type DownloadSuccessEvent = {
    [key: string]: never;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type PostDownloadRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    url: string;
    /**
     * Pass additional args to yt-dlp
     */
    yt_dlp_args?: string;
};

export type SortDownloadsResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    files_with_errors: Array<string> | null;
    moved_files: Array<string> | null;
};

export type DownloadResponseBodyWritable = {
    message: string;
    task_id: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type PostDownloadRequestWritable = {
    url: string;
    /**
     * Pass additional args to yt-dlp
     */
    yt_dlp_args?: string;
};

export type SortDownloadsResponseBodyWritable = {
    files_with_errors: Array<string> | null;
    moved_files: Array<string> | null;
};

export type PostApiV1DownloadData = {
    body: PostDownloadRequestWritable;
    path?: never;
    query?: never;
    url: '/api/v1/download';
};

export type PostApiV1DownloadErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostApiV1DownloadError = PostApiV1DownloadErrors[keyof PostApiV1DownloadErrors];

export type PostApiV1DownloadResponses = {
    /**
     * OK
     */
    200: DownloadResponseBody;
};

export type PostApiV1DownloadResponse = PostApiV1DownloadResponses[keyof PostApiV1DownloadResponses];

export type DownloadStreamData = {
    body?: never;
    path: {
        task_id: string;
    };
    query?: never;
    url: '/api/v1/download/stream/{task_id}';
};

export type DownloadStreamErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DownloadStreamError = DownloadStreamErrors[keyof DownloadStreamErrors];

export type DownloadStreamResponses = {
    /**
     * Server Sent Events
     * Each oneOf object in the array represents one possible Server Sent Events (SSE) message, serialized as UTF-8 text according to the SSE specification.
     */
    200: Array<{
        data: DownloadNotFoundEvent;
        /**
         * The event name.
         */
        event: 'download_not_found';
        /**
         * The event ID.
         */
        id?: number;
        /**
         * The retry time in milliseconds.
         */
        retry?: number;
    } | {
        data: DownloadSuccessEvent;
        /**
         * The event name.
         */
        event: 'download_success';
        /**
         * The event ID.
         */
        id?: number;
        /**
         * The retry time in milliseconds.
         */
        retry?: number;
    } | {
        data: DownloadStdoutNewLineEvent;
        /**
         * The event name.
         */
        event: 'new_line';
        /**
         * The event ID.
         */
        id?: number;
        /**
         * The retry time in milliseconds.
         */
        retry?: number;
    }>;
};

export type DownloadStreamResponse = DownloadStreamResponses[keyof DownloadStreamResponses];

export type PostApiV1SortDownloadsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/sort-downloads';
};

export type PostApiV1SortDownloadsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostApiV1SortDownloadsError = PostApiV1SortDownloadsErrors[keyof PostApiV1SortDownloadsErrors];

export type PostApiV1SortDownloadsResponses = {
    /**
     * OK
     */
    200: SortDownloadsResponseBody;
};

export type PostApiV1SortDownloadsResponse = PostApiV1SortDownloadsResponses[keyof PostApiV1SortDownloadsResponses];

export type GetApiV1StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status';
};

export type GetApiV1StatusErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetApiV1StatusError = GetApiV1StatusErrors[keyof GetApiV1StatusErrors];

export type GetApiV1StatusResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetApiV1StatusResponse = GetApiV1StatusResponses[keyof GetApiV1StatusResponses];
