// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type AuthStatusBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    authenticated: boolean;
    username?: string;
};

export type AuthSuccessBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
    success: boolean;
    username: string;
};

export type DownloadResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    message: string;
    task_id: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type LoginRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Password
     */
    password: string;
    /**
     * Username
     */
    username: string;
};

export type PostDownloadRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    url: string;
    /**
     * Pass additional args to yt-dlp
     */
    yt_dlp_args?: string;
};

export type SortDownloadsResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    files_with_errors: Array<string> | null;
    moved_files: Array<string> | null;
};

export type AuthStatusBodyWritable = {
    authenticated: boolean;
    username?: string;
};

export type AuthSuccessBodyWritable = {
    message: string;
    success: boolean;
    username: string;
};

export type DownloadResponseBodyWritable = {
    message: string;
    task_id: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type LoginRequestBodyWritable = {
    /**
     * Password
     */
    password: string;
    /**
     * Username
     */
    username: string;
};

export type PostDownloadRequestWritable = {
    url: string;
    /**
     * Pass additional args to yt-dlp
     */
    yt_dlp_args?: string;
};

export type SortDownloadsResponseBodyWritable = {
    files_with_errors: Array<string> | null;
    moved_files: Array<string> | null;
};

export type PostApiV1AuthLoginData = {
    body: LoginRequestBodyWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostApiV1AuthLoginError = PostApiV1AuthLoginErrors[keyof PostApiV1AuthLoginErrors];

export type PostApiV1AuthLoginResponses = {
    /**
     * OK
     */
    200: AuthSuccessBody;
};

export type PostApiV1AuthLoginResponse = PostApiV1AuthLoginResponses[keyof PostApiV1AuthLoginResponses];

export type PostApiV1AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type PostApiV1AuthLogoutErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostApiV1AuthLogoutError = PostApiV1AuthLogoutErrors[keyof PostApiV1AuthLogoutErrors];

export type PostApiV1AuthLogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiV1AuthLogoutResponse = PostApiV1AuthLogoutResponses[keyof PostApiV1AuthLogoutResponses];

export type GetApiV1AuthStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/status';
};

export type GetApiV1AuthStatusErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetApiV1AuthStatusError = GetApiV1AuthStatusErrors[keyof GetApiV1AuthStatusErrors];

export type GetApiV1AuthStatusResponses = {
    /**
     * OK
     */
    200: AuthStatusBody;
};

export type GetApiV1AuthStatusResponse = GetApiV1AuthStatusResponses[keyof GetApiV1AuthStatusResponses];

export type PostApiV1DownloadData = {
    body: PostDownloadRequestWritable;
    path?: never;
    query?: never;
    url: '/api/v1/download';
};

export type PostApiV1DownloadErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostApiV1DownloadError = PostApiV1DownloadErrors[keyof PostApiV1DownloadErrors];

export type PostApiV1DownloadResponses = {
    /**
     * OK
     */
    200: DownloadResponseBody;
};

export type PostApiV1DownloadResponse = PostApiV1DownloadResponses[keyof PostApiV1DownloadResponses];

export type PostApiV1SortDownloadsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/sort-downloads';
};

export type PostApiV1SortDownloadsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PostApiV1SortDownloadsError = PostApiV1SortDownloadsErrors[keyof PostApiV1SortDownloadsErrors];

export type PostApiV1SortDownloadsResponses = {
    /**
     * OK
     */
    200: SortDownloadsResponseBody;
};

export type PostApiV1SortDownloadsResponse = PostApiV1SortDownloadsResponses[keyof PostApiV1SortDownloadsResponses];

export type GetApiV1StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status';
};

export type GetApiV1StatusErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetApiV1StatusError = GetApiV1StatusErrors[keyof GetApiV1StatusErrors];

export type GetApiV1StatusResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetApiV1StatusResponse = GetApiV1StatusResponses[keyof GetApiV1StatusResponses];
